name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        run: |
          set -x
          cat <<EOF > ".github/workflows/${GITHUB_JOB}_${GITHUB_RUN_ID}.yml"
          name: valid
          on:
            workflow_dispatch:
          jobs:
            run:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v4
          EOF

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true

      - name: Verify
        env:
          OUTCOME: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${OUTCOME}" = "success"

  test-error:
    name: Test error
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        run: |
          set -x
          cat <<EOF > ".github/workflows/${GITHUB_JOB}_${GITHUB_RUN_ID}.yml"
          name: invalid
          on:
            workflow_dispatch:
          EOF

      - name: Exercise
        id: exercise
        uses: ./
        continue-on-error: true

      - name: Verify
        env:
          OUTCOME: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${OUTCOME}" = "failure"
